<%@ Page Title="" Language="C#" MasterPageFile="~/Doctor/DoctorMaster.Master" AutoEventWireup="true" CodeBehind="UploadHealthEducationVideos.aspx.cs" Inherits="DBProject.Doctor.UploadHealthEducationVideos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>新增衛教影片</title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Cp1" runat="server">
    <asp:GridView            
                ID="dgvVideoList"
                AutoGenerateDeleteButton="True" 
                EnableViewState="False" 
                OnRowDeleting="DeleteVideo_Click"
                OnRowCommand="dgvVideoList_RowCommand"
                OnRowDataBound="dgvVideoList_RowDataBound"
                runat="server" 
                BackColor="White" 
                BorderColor="#DEDFDE" 
                BorderStyle="Double" 
                BorderWidth="2px" 
                CellPadding="8" 
                Caption="衛教影片清單" 
                CaptionAlign="Top" 
                HorizontalAlign="Center" 
                Width="380px"  
                GridLines="Horizontal" 
                CellSpacing="3" 
                AutoGenerateSelectButton="True"
            >

                <AlternatingRowStyle BackColor="White" />
                <FooterStyle BackColor="#CCCC99" />
                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                <RowStyle BackColor="#F7F7DE" Width="100%" />
                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                <SortedAscendingHeaderStyle BackColor="#848384" />
                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                <SortedDescendingHeaderStyle BackColor="#575357" />

            </asp:GridView>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Cp2" runat="server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="Cp3" runat="server">
</asp:Content>
