<%@ Page Title="" Language="C#" MasterPageFile="~/Doctor/DoctorMaster.Master" AutoEventWireup="true" CodeBehind="UploadHealthEducationVideos.aspx.cs" Inherits="DBProject.Doctor.UploadHealthEducationVideos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>新增衛教影片</title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Cp1" runat="server">
    <asp:GridView            
                ID="dgvVideoList"
                AutoGenerateDeleteButton="True" 
                AutoGenerateSelectButton="true"
                EnableViewState="False" 
                OnRowDeleting="DeleteVideo_Click" 
                OnSelectedIndexChanging="SelectVideo_Click"
                OnRowDataBound="dgvVideoList_RowDataBound"
                runat="server" 
                BackColor="White" 
                BorderColor="#DEDFDE" 
                BorderStyle="Double" 
                BorderWidth="2px" 
                CellPadding="8" 
                Caption="衛教影片清單" 
                CaptionAlign="Top" 
                HorizontalAlign="Center" 
                Width="380px"  
                GridLines="Horizontal" 
                CellSpacing="3" 
            >

                <AlternatingRowStyle BackColor="White" />
                <FooterStyle BackColor="#CCCC99" />
                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                <RowStyle BackColor="#F7F7DE" Width="100%" />
                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                <SortedAscendingHeaderStyle BackColor="#848384" />
                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                <SortedDescendingHeaderStyle BackColor="#575357" />

            </asp:GridView>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Cp2" runat="server">
    <br />
    <div class="form-group">
        <table class="table table-bordered">
            <caption> 【影片資料編輯】 </caption>
                <thead>                   
                </thead>
                   
                <tbody>
                    <asp:HiddenField ID="hfUploadVideoID" runat="server" />
                    <tr>
                        <td>影片主題</td>
                        <td><asp:TextBox ID="txtVideoTitle" runat="server" type="text" class="form-username form-control" placeholder="請填寫影片主題" ></asp:TextBox></td>
                    </tr>
                    <tr>
                        <td>影片類別</td>
                        <td>
                            <select id="SelectCategories" runat="server">
                                <option>體溫</option>
                                <option>脈搏/心跳</option>
                                <option>血氧</option>
                                <option>血糖</option>
                                <option>血壓</option>
                                <option>其他不分類</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>影片網址</td>
                        <td><asp:TextBox ID="txtVideoURL" runat="server" type="text" class="form-username form-control" placeholder="請填寫影片來源網址" ></asp:TextBox></td>
                    </tr>
                    <tr>
                        <td>編輯日期</td>
                        <td><asp:Label ID="lblUploadDate" runat="server" ></asp:Label></td>
                    </tr>

                </tbody>
        </table>
    </div>
    <asp:button Text ="儲存資料"  runat="server" type="submit" class="btn btn-primary center-block" OnClick="SentHEVideoData_Click"></asp:button>
				           
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="Cp3" runat="server">
</asp:Content>
