<%@ Page Title="" Language="C#" MasterPageFile="~/Doctor/DoctorMaster.Master" AutoEventWireup="true" CodeBehind="ViewPatientMeasurementDatas.aspx.cs" Inherits="DBProject.Doctor.ViewPatientMeasurementDatas" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>病人量測資料查詢</title> 

    <style type = "text/css">

    .outer {
       margin-left:20%;
       display:inline-block;
  
     

    }
    .mydiv
    {
        display:inline-block;
    }

    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Cp1" runat="server">
    <div class="outer">
        <div>
        
            <asp:Label ID="lblSerchTag" runat="server" Text="姓名 : "></asp:Label>
            <asp:TextBox ID="txtSearch" runat="server" />
            <asp:button Text ="查詢"  runat="server" type="submit" class="btn btn-primary"  OnClick="Search_btn" ></asp:button>
            <br />
            <asp:HiddenField ID="hfSearchState" runat="server" />
            <asp:Label ID="Msg" runat="server" Font-Bold="True"></asp:Label>
        

            <asp:GridView            
                ID="dgvPatientListInfo"
                AutoGenerateDeleteButton ="False"
                EnableViewState="False"
                OnRowCommand ="dgvPatientListInfo_RowCommand"
                OnRowDataBound="dgvPatientListInfo_RowDataBound"
                runat="server" 
                BackColor="White" 
                BorderColor="#336666" 
                BorderStyle="Double" 
                BorderWidth="2px" 
                CellPadding="8" 
                Caption="病人清單" 
                CaptionAlign="Top" 
                HorizontalAlign="Center" 
                Width="380px"  
                GridLines="Horizontal" 
                CellSpacing="3" 
                AutoGenerateSelectButton="True"
            >

                <FooterStyle BackColor="White" ForeColor="#333333" />
                <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle ForeColor="#333333" BorderStyle="solid" BorderWidth="4px" BackColor="White" />
                <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F7F7F7" />
                <SortedAscendingHeaderStyle BackColor="#487575" />
                <SortedDescendingCellStyle BackColor="#E5E5E5" />
                <SortedDescendingHeaderStyle BackColor="#275353" />

            </asp:GridView>

        </div>

    </div>
    
    <div style="display:inline-block; float:right;margin-right:10%" runat="server" id="mydiv"></div>

</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Cp2" runat="server">
    <!------------------Styling------------------>
    <link rel="stylesheet" href="/assets/css/grid-view.css"/>

    <asp:GridView ID="TPatientMessurementDatasGrid" runat="server" class = "GridView-d" CellPadding="4" ForeColor="Black" GridLines="Vertical" Width="100%"
        EnableViewState ="False"
        AutoGenerateSelectButton="True" 
        OnRowCommand="TPatientMessurementDatasGrid_RowCommand"
        OnRowDataBound="TPatientMessurementDatasGrid_RowDataBound"
        BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px"
        
    >

        <AlternatingRowStyle BackColor="White" />
        <FooterStyle BackColor="#CCCC99" />
        <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
        <RowStyle BackColor="#F7F7DE" Width="100%" />
        <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#FBFBF2" />
        <SortedAscendingHeaderStyle BackColor="#848384" />
        <SortedDescendingCellStyle BackColor="#EAEAD3" />
        <SortedDescendingHeaderStyle BackColor="#575357" />
          
        <Columns>
            <asp:TemplateField HeaderText = "No." ItemStyle-Width="50">
                <ItemTemplate>
                    <asp:Label ID="lblRowNumber" Text='<%# Container.DataItemIndex + 1 %>' runat="server" />
                </ItemTemplate>

            <ItemStyle Width="50px"></ItemStyle>
            </asp:TemplateField>
        </Columns>


    </asp:GridView>

    <br />

    <div class="form-group">
    <asp:Label ID="Label1" runat="server" Text="表單填寫時間 : "></asp:Label><asp:Label ID="lbMessurementDateF" runat="server" Text=""></asp:Label>
    <br /><br /><asp:Label ID="Label3" runat="server" Text="身高量測時間 : "></asp:Label><asp:Label ID="lbHeightMessurementDate" runat="server" Text=""></asp:Label>
    <br /><br /><asp:Label ID="Label5" runat="server" Text="體重量測時間 : "></asp:Label><asp:Label ID="lbWeightMessurementDate" runat="server" Text=""></asp:Label>
    <br /><br /><asp:Label ID="Label7" runat="server" Text="BMI量測時間 : "></asp:Label><asp:Label ID="lbBMIMessurementDate" runat="server" Text=""></asp:Label>
    <br /><br /><asp:Label ID="Label9" runat="server" Text="體溫量測時間 : "></asp:Label><asp:Label ID="lbTemperatureMessurementDate" runat="server" Text=""></asp:Label>
    <br /><br /><asp:Label ID="Label11" runat="server" Text="脈搏與心跳量測時間 : "></asp:Label><asp:Label ID="lbHBMessurementDate" runat="server" Text=""></asp:Label>
    <br /><br /><asp:Label ID="Label13" runat="server" Text="血氧量測時間 : "></asp:Label><asp:Label ID="lbBOMessurementDate" runat="server" Text=""></asp:Label>
    <br /><br /><asp:Label ID="Label15" runat="server" Text="血糖量測時間 : "></asp:Label><asp:Label ID="lbPGMessurementDate" runat="server" Text=""></asp:Label>
    <br /><br /><asp:Label ID="Label17" runat="server" Text="血壓量測時間 : "></asp:Label><asp:Label ID="lbBPMessurementDate" runat="server" Text=""></asp:Label>
    </div>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="Cp3" runat="server">
</asp:Content>
